apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-phpmyadmin-deployment
  namespace: kustomize
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: db
            - name: PMA_PORT
              value: "3306"
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-postgres-pass
                  key: password

