version: '3.1'
services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=storedb
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose: 
      - 5432
    networks:
      - apinetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - apinetwork

  fastapi:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:5000
    depends_on:
      - db
    networks:
      - apinetwork

volumes:
  postgres_data:

networks:
  apinetwork:
    driver: bridge
