apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-fastapi-issuer
  annotations:
{{ toYaml .Values.clusterissuer.annotations | indent 4 }}
spec:
  acme:
    email: {{ .Values.clusterissuer.acmeEmail }}
    server: {{ .Values.clusterissuer.acmeServer }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.privateKeySecretRefName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterissuer.solverIngressClass }}

