apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Release.Name }}-fastapi-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Release.Name }}-fastapi
 minReplicas: {{ .Values.hpa.minReplicas }}
 maxReplicas: {{ .Values.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
