apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: db
            - name: PMA_PORT
              value: "3306"
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-pass
                  key: password
