apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-datascientest
  namespace: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

